### ISSUE TITLE
user input부분 추가 시 back, frontend TODO list

### ISSUE THREAD

**Issue by illhyhl1111** [MKRoughDiamond/InfoVis20202#21]
* 프런트, 백엔드 부분에서 구현해야될 부분 TODO로 표기함
  * front: 이미지 업데이트해야될 일 있을때마다 updateSectionC1 호출 **(line 585)**
  * front: C1에서 유저 입력 들어온 뒤 나머지 B, C2 부분 update **(line 566)**
  * back: opcode로 encode_img 받아서 latent_imgs와 같은 출력 + latent value 반환 **(line 544)**

![image](https://user-images.githubusercontent.com/15259969/100999983-a7221400-35a0-11eb-9ec1-4815fdd47dd6.png)

* 지금은 저번주 회의대로 추가구현부분 오른쪽 끝에 박아뒀는데, line 80~102 부분을 적당히 C 안에 넣으면 됨

![image](https://user-images.githubusercontent.com/15259969/101000412-39c2b300-35a1-11eb-8199-8d76ba136ed3.png)

* 사용법
  * 첫번째 버튼은 이미지 업로드. 
  * 두번째 버튼은 이미지 그리기, 버튼 누르면 활성화되고 다시 누르면 비활성화. 대표 latent가 바뀔 때 비활성상태로 돌아감.
  * 세번째 버튼은 이미지 서버로 보내기 -> 응답받아서 대표 latent 및 프런트엔드 update. 백엔드 구현이 완료되면 돌아갈건데 지금은 안됨.

**Comment by MKRoughDiamond** [comment]
완료 된 것 같습니다.
