### ISSUE TITLE
frontend todo?

### ISSUE THREAD

**Issue by illhyhl1111** [MKRoughDiamond/InfoVis20202#34]
## B2
![image](https://user-images.githubusercontent.com/15259969/101316288-91159b80-389f-11eb-8a5e-3ca9050741f8.png)
* 6번 dimension이 굵기담당인데 6번 넘버링이 아래에 있음. 둘이 바뀌는게 더 보기 좋을듯
* 가능하면 latent상에서 scale 좀 표기해줬으면 함. 가장 간단하게는 저렇게 양쪽 꼭지점에 최대 변화량 적어놓는거

## C2
![image](https://user-images.githubusercontent.com/15259969/101316061-1ea4bb80-389f-11eb-90c5-1281a56563fa.png)
* 지금 뭐가먼지 몰겠음
* 왼쪽에는 dimension number
* 위쪽에는 delta값
* 행마다 간격 조금만 띄워주거나, 이미지가 너무 작아질거같으면 행 사이에 선이라도 그어서 시각적으로 분리좀 해줬으면

![image](https://user-images.githubusercontent.com/15259969/101316665-434d6300-38a0-11eb-9bbb-a054a4a1904d.png)
* 지금은 이미지 표기 개수가 11개라 꽉 차는데, 그게 줄어들 경우 가운데 정렬로 양쪽 사이드를 비워두는게 좋을거같음

## B1
![image](https://user-images.githubusercontent.com/15259969/101316730-68da6c80-38a0-11eb-94dd-01ada7f77481.png)
* 마찬가지로 latent값이랑 축 스케일 구분좀
* 축 넘버링도. (볼드체로?)

@greeksharifa 부탁드림다

**Comment by greeksharifa** [comment]
어제 완료
